### ISSUE TITLE
HTML5SourceAdapter ignores Doctype definition

### ISSUE THREAD

**Issue by hason** [goetas/twital#15]
``` html
<!DOCTYPE html>
<html>
  <head>
    <title>My Webpage</title>
  </head>
  <body>foo</body>
</html>
```

is transformed to

``` html
<html>
  <head>
    <title>My Webpage</title>
  </head>
  <body>foo</body>
</html>
```

**Comment by Stormcloud** [comment]
This appears to still be an issue. Is there a way to include the doctype in a template?

**Comment by goetas** [comment]
@Stormcloud are you sure about it? https://github.com/goetas/twital/pull/17/files#diff-d19fc92e381ccbe7981b41585ed95dd9 is the test to ensure it. Can you share a not-working example?

**Comment by Stormcloud** [comment]
I have found the problem. If the doctype declaration is in lower case, it gets stripped from the output.
So `<!DOCTYPE html>` works, but `<!doctype html>` doesn't.
An error on my part, since upper case is the correct form.
