### ISSUE TITLE
Missing SourceEvent

### ISSUE THREAD

**Issue by soukiii** [goetas/twital#30]
I have noticed unknown *SourceEvent* in  src/Goetas/Twital/EventSubscriber/CustomNamespaceSubscriber.php

Maybe missing *use Goetas\Twital\EventDispatcher\SourceEvent;*?

**Comment by goetas** [comment]
It should be `Goetas\Twital\EventDispatcher\SourceEvent`. At the moment `CustomNamespaceSubscriber` class is an alternative version of `CustomNamespaceRawSubscriber` but is not used at all.

`CustomNamespaceSubscriber` tries to add custom namespaces at DOM level (`CustomNamespaceRawSubscriber` does the same but at XML level)... but I've found some problems to make it work, so at the moment is not used...
