### ISSUE TITLE
How to make an child template be valid XHTML

### ISSUE THREAD

**Issue by msgilligan** [goetas/twital#39]
I'm looking at using Twital to implement the "page decorator"/layout pattern, as can be done in Thymeleaf with the [Thymeleaf Layout Dialect](https://github.com/ultraq/thymeleaf-layout-dialect#thymeleaf-layout-dialect).

"Template Inheritence" looks very similar to what I want (and at first glance I mistakenly thought it was _exactly_ what I want.)  What I'm looking for is for both the base template and the child template to be valid XHTML (or better yet valid HTML, as in Thymeleaf 3's [Full HTML5 markup support](http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html)

Is there a way to make a child template that is valid XHTML?

**Comment by goetas** [comment]
Are you talking about the output of the rendering process? or is it more about the initial template file? Which one do you want to be XHTML valid?

**Comment by msgilligan** [comment]
At a minimum I'd like the input templates ("base" and "child") to be (X)HTML. The output should be HTML5.
