### ISSUE TITLE
Symfony 3 support

### ISSUE THREAD

**Issue by msgilligan** [goetas/twital#40]
Is Symfony 3 supported? Is there any documentation on how to use Twital with Symfony 3?

**Comment by goetas** [comment]
Twital itself depends only on the event dispatcher from symfony 3, so yes, it is. 

Regarding the twital bundle for symfony, please refer to https://github.com/goetas/twital-bundle/issues/6

**Comment by goetas** [comment]
> there are no differences between 2.x and 3.x regarding on how to use twital.

For more info have a look info http://twital.readthedocs.io/ and http://twital.readthedocs.io/

**Comment by msgilligan** [comment]
Thanks for the quick responses to all of my Issues!
