### ISSUE TITLE
Infinite loop with FixHtmlEntitiesInExpressionSubscriber

### ISSUE THREAD

**Issue by soukicz** [goetas/twital#48]
I was using version 0.1.8 and I was using this test with `FixHtmlEntitiesInExpressionSubscriber`:
```xml
<!-- input -->
<div><img src="{{ true ? "/b/x.jpg"}}"></div>

<!-- expected -->
<div><img src="/b/x.jpg"></div>
```

It work fine with 0.1.8 but after upgrading to 0.1.9 or 1.0.0. this code stucks Twital in infinite loop (probably).

**Comment by goetas** [comment]
In 0.1.9 https://github.com/goetas/twital/pull/35 was merged. a relatively big PR.

Working on it on https://github.com/goetas/twital/pull/49

**Comment by soukicz** [comment]
Ha, it is because of the whitespace! I thought it was because of mixing quotes...

**Comment by hason** [comment]
Fixed in #50.

**Comment by goetas** [comment]
release https://github.com/goetas/twital/releases/tag/v1.0.1

**Comment by soukicz** [comment]
Thank you!
