### ISSUE TITLE
Question: own twig-functions don´t work

### ISSUE THREAD

**Issue by rolfjoseph** [goetas/twital#54]
<div t:for="i in range(0, 3)">
{{ i }},
</div>

This code runs perfectly, but my own twig-functions over twig extensions not.
At twig self my functions works also perfectly.

<small>
	{{ Datetime(activity.created_date) }}
</small>

This code makes under twital the follow error:
Fatal error: Uncaught Twig_Error_Syntax: Unknown "Datetime" function.

<small>
	Datetime(activity.created_date)
</small>

This code runs, but without any output.

What can i do to solve this problem ?

**Comment by goetas** [comment]
twig functions defined by an extension or defined as a macro? 
are you using symfony?

The error
> Fatal error: Uncaught Twig_Error_Syntax: Unknown "Datetime" function.

suggests that your extension is not loaded into the twig core... can you share the way you are registering your extension to twig?

**Comment by rolfjoseph** [comment]
It´s by an extension !

**Comment by rolfjoseph** [comment]
$this->debug = (bool) $options['debug'];
        $this->charset = strtoupper($options['charset']);
        $this->baseTemplateClass = $options['base_template_class'];
        $this->strictVariables = (bool) $options['strict_variables'];

        $this->addExtension(new Twig_Extension_Core());
        $this->addExtension(new Twig_Extension_Escaper($options['autoescape']));
        $this->addExtension(new Twig_Extension_Optimizer($options['optimizations']));

        // Einbindung eigener Twig-Funktionen
        $this->addExtension(new Twig_Extension_Lib());

        $this->staging = new Twig_Extension_Staging();

**Comment by goetas** [comment]
are you using symfony?

**Comment by goetas** [comment]
what is `$this` ?

**Comment by rolfjoseph** [comment]
I´am not using symfony and $this ist the twig environment.

**Comment by rolfjoseph** [comment]
My project is https://github.com/rolfjoseph/openwebsoccer2017
I want use your twial for the templates.

At this moment i think too, that´s a path problem.

**Comment by goetas** [comment]
are you instantiating twital as suggested in the documentation?

```
$fileLoader = new Twig_Loader_Filesystem('/path/to/templates');
$twitalLoader = new TwitalLoader($fileLoader);

$twig = new Twig_Environment($twitalLoader); // <<< here you should put your twig class name
echo $twig->render('demo.twital.html', array('name' => 'John'));
```

**Comment by goetas** [comment]
> My project is https://github.com/rolfjoseph/openwebsoccer2017

Please use a framework :smile:  the result will be much better... any framework

**Comment by rolfjoseph** [comment]
Is use a universal code to load the classname:

<?php
require_once './vendor/autoload.php';
use Goetas\Twital\TwitalLoader;

define('TEMPLATE_MODUL_FOLDER',__DIR__);

$directory = TEMPLATE_MODUL_FOLDER . '/';
		$files = glob($directory . '*');
		foreach($files as $file){
			if(is_dir($file)){
				$twigarray[]=$file;
			}
		}

$fileLoader = new Twig_Loader_Filesystem($twigarray);
$twitalLoader = new TwitalLoader($fileLoader);

$twig = new Twig_Environment($twitalLoader);
echo $twig->render('demo.twital', array('name' => 'John'));

Thank you a the moment, i hope i can resolve this now. The older versions of  my project runs perfectly with twig without any framework.

I find your twital ist the best way to generate the templates for better understanding and controlling the templates.

Great job !

**Comment by goetas** [comment]
The problem is `Twig_Environment` in your code. instead of `Twig_Environment` should be something as `MYTwigEnvironment`.

`MYTwigEnvironment` is the name of your class where you wrote +


```php
        // Einbindung eigener Twig-Funktionen
        $this->addExtension(new Twig_Extension_Lib());
```

```

**Comment by rolfjoseph** [comment]
I have found the problem:

 public function getFunctions()
    {
        return array(
            new Twig_SimpleFunction('Datetime', 'Datetime'),
        );
    }

The Datetime must have defined with the getFunctions to tell twital that twig has this function.
Until this wasn´t needed for my twig environment, because ist was found under the twig functions-set.

{{ Datetime(1487443680) }} gives now the right output 18.02.2017

I have to rewrote some funtions they are not run a the moment with twital.

Thank you for your comments and i hope some other help this way too.

**Comment by rolfjoseph** [comment]
Now my last comment to this issue. The following code do i need to work without any changes at my own library:

```
<?php
require_once '../vendor/autoload.php';
use Goetas\Twital\TwitalLoader;

// This file and the Twital-File to render at the same directory
$fileLoader = new Twig_Loader_Filesystem(__DIR__);
$twitalLoader = new TwitalLoader($fileLoader);

// Twital init
$twital = new Twig_Environment($twitalLoader);

// Register all PHP/Twig functions and filters for using at Twital
$twital->registerUndefinedFilterCallback(function($name) {
if (function_exists($name)) {
		return new Twig_SimpleFilter($name,function() use($name) {
		return call_user_func_array($name,func_get_args());
		});
	}
	return false;
});
$twital->registerUndefinedFunctionCallback(function($name) {
if (function_exists($name)) {
		return new Twig_SimpleFunction($name,function() use($name) {
		return call_user_func_array($name,func_get_args());
		});
	}
	return false;
});

// Rendering the Tewital or Twig Template
echo $twital->render('demo.twital.html', array('name' => 'John'));
```
