### ISSUE TITLE
The <t:omit> node sometimes removes children (but not their children) with t:block=

### ISSUE THREAD

**Issue by abcarroll** [goetas/twital#55]
The simplest way I can explain this is with the following tests (intended for CoreNodesTest.php around line 135-137):

```
// Passes, as you'd expect
array('<t:omit><div>foo</div><div>bar</div></t:omit>', '<div>foo</div><div>bar</div>'),
// Fails
array('<t:omit><div t:block="aaa">foo</div><div t:block="bbb">bar</div></t:omit>', '<div>{% block aaa %}foo{% endblock %}</div><div>{% block bbb %}bar{% endblock %}</div>'),
// Fails
array('<t:omit><div t:block="aaa"><h1>Hello, World!</h1><p>foo <em>bar</em></p></div><div t:block="bbb">bar</div></t:omit>', '<div>{% block aaa %}<h1>Hello, World!</h1><p>foo <em>bar</em></p>{% endblock %}</div><div>{% block bbb %}bar{% endblock %}</div>'),
```

The second test will fail when by all means it should pass.  The third test/line input above, formatted:

````
<t:omit>
    <div t:block="aaa">
        <h1>Hello, World!</h1>
        <p>foo <em>bar</em></p>
    </div>
    <div t:block="bbb">
        bar
    </div>
</t:omit>
````

You would expect to be compiled to:
````
    <div>
    {% block aaa %}
        <h1>Hello, World!</h1>
        <p>foo <em>bar</em></p>
    {% endblock %}
    </div>
    <div>
    {% block bbb %}
        bar
    {% endblock% }
    </div>
````

Yet, instead, it results in something like:

````
    {% block aaa %}
        <h1>Hello, World!</h1>
        <p>foo <em>bar</em></p>
    {% endblock %}
    {% block bbb %}
        bar
    {% endblock% }
````

Basically, the tags *directly* below the `<t:omit>` is mysteriously removed when it also contains a `t:block` attribute (and, possibly others).  In this example, it is of course the two `<div>` tags.

I am attempting to fix this --- wrapping it in an additional `<t:omit>` is a quick-fix/hack, but it's quite perplexing as to why it occurs in the first place.

From the other tests/examples, it certainly seems like this was not the intended behavior. 

Any suggestions/hints?

**Comment by goetas** [comment]
hmm... weird. will have a look soon!
