### ISSUE TITLE
Request new Release w/ updated deps (masterminds/html5)

### ISSUE THREAD

**Issue by na-oma** [goetas/twital#69]
Hi, we are using this library to produce templated PDF files from HTML through Snappy.
HTML parsing takes double the time than generation of the PDF itself.

As there are quite a few performance improvements in masterminds/html5, can we get a new release with updated dependencies, at least masterminds/html5? Or were any incompatibilities introduced?

**Comment by goetas** [comment]
since de dependency here is expressed using ^, any 2.x release of masterminds/htmll5 is already compatible. see https://github.com/goetas/twital/blob/a65afad379f78d95d9bc9749c13de4e65ee19a90/composer.json#L20

just run `composer update` and should already work
